/**
 * Propiedades de un examen.
 * @typedef {Object} Exam
 * @property {string} id - Identificador único.
 * @property {string} title - Título del examen (ej. "Primer Parcial").
 * @property {string} subject - Materia (ej. "Matemáticas").
 * @property {string} date - Fecha en formato YYYY-MM-DD.
 * @property {string} time - Hora del examen.
 * @property {string} location - Lugar físico.
 * @property {string[]} topics - Lista de temas a estudiar.
 * @property {string} [notes] - Notas adicionales opcionales.
 */

import { useState, useEffect } from 'react';
import { Exam } from '../types';
import { parseAndValidateExams } from '../utils/examImport';
import { exportExamsToJson, exportExamsToHtml } from '../utils/examExport';
import { generateStudentBuild } from '../utils/studentBuild';

const getTodayISO = () => {
    const d = new Date();
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
};

/**
 * Hook personalizado para manejar la lógica de negocio de los exámenes.
 * Encapsula el estado, persistencia en localStorage y operaciones CRUD.
 * 
 * @returns {Object} Objeto con estado y funciones manipuladoras.
 * @property {Exam[]} exams - Lista actual de exámenes.
 * @property {Function} addOrUpdateExam - Función para crear o editar un examen.
 * @property {Function} deleteExam - Función para eliminar un examen por ID.
 * @property {Object} stats - Estadísticas calculadas (total, pendientes, hoy).
 * @property {Function} importExams - Importa exámenes desde un string JSON.
 * @property {Function} exportExams - Exporta exámenes a un string JSON.
 */
export const useExams = () => {
    const [exams, setExams] = useState<Exam[]>(() => {
        // 1. DATA INJECTION (Student Build)
        // Check if there is injected data in the window object (generated by build script)
        if (typeof window !== 'undefined' && window.PLANNER_DATA) {
            return window.PLANNER_DATA;
        }

        // 2. READ ONLY MODE (Dev / Legacy)
        // En modo "Read-Only" (Estudiante), ignoramos el localStorage y cargamos siempre el cronograma oficial
        if (import.meta.env.VITE_READ_ONLY === 'true') {
            // ... logic for legacy read-only if needed, or remove if supplanted by injection
        }

        // 3. TEACHER MODE (LocalStorage)
        if (import.meta.env.VITE_READ_ONLY !== 'true') {
            const savedExams = localStorage.getItem('exams');
            if (savedExams) {
                try {
                    return JSON.parse(savedExams);
                } catch (e) {
                    console.error('Error parsing saved exams:', e);
                }
            }
        }

        // Datos por defecto (Cronograma Oficial o Mocks)
        return [
            {
                id: '1',
                title: 'Primer Parcial',
                subject: 'Arquitectura de Datos',
                date: getTodayISO(),
                time: '10:00 AM',
                location: 'Laboratorio de Cómputo 3',
                topics: ['SQL', 'NoSQL', 'ETL', 'Data Warehousing'],
                notes: 'Traer identificación oficial.'
            },
            {
                id: '2',
                title: 'Segundo Parcial',
                subject: 'Inteligencia Artificial',
                date: '2026-06-15', // Fecha actualizada a 2026
                time: '12:30 PM',
                location: 'Aula 201',
                topics: ['Deep Learning', 'Neural Networks', 'NLP'],
                notes: 'Examen a libro abierto.'
            },
            {
                id: '3',
                title: 'Proyecto Final',
                subject: 'Desarrollo Web Avanzado',
                date: '2026-07-20',
                time: '18:00 PM',
                location: 'Auditorio Principal',
                topics: ['React', 'TypeScript', 'Tailwind', 'A11y', 'Performance'],
                notes: 'Presentación grupal de 20 minutos. Traer laptop y adaptador HDMI.',
                distributionUrl: 'https://example.com/aulas',
                formUrl: 'https://example.com/entrega'
            },
            {
                id: '4',
                title: "Examen de Diagnóstico",
                subject: "Alfabetización Digital",
                date: "2025-12-29",
                time: "08:00",
                location: "B2-10",
                topics: [],
                notes: "Este examen no tiene valor sumativo",
                formUrl: "",
            }
        ].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
    });

    useEffect(() => {
        localStorage.setItem('exams', JSON.stringify(exams));
    }, [exams]);

    const addOrUpdateExam = (exam: Exam) => {
        setExams(prev => {
            const exists = prev.some(e => e.id === exam.id);
            if (exists) {
                return prev.map(e => e.id === exam.id ? exam : e).sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
            }
            return [...prev, exam].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
        });
    };

    const deleteExam = (id: string) => {
        setExams(prev => prev.filter(e => e.id !== id));
    };

    const getStats = () => {
        const todayStr = getTodayISO();
        return {
            total: exams.length,
            // Comparar fechas como strings YYYY-MM-DD es seguro aquí
            upcoming: exams.filter(e => e.date > todayStr).length,
            today: exams.filter(e => e.date === todayStr).length
        };
    };

    const importExams = (jsonContent: string) => {
        const result = parseAndValidateExams(jsonContent);
        if (result.success && result.data?.exams) {
            setExams(result.data.exams);
        }
        return result;
    };

    const exportExams = (config?: any) => {
        return exportExamsToJson(exams, config);
    };

    const exportExamsToHtmlHandler = () => {
        return exportExamsToHtml(exams);
    };

    const generateStudentBuildHandler = () => {
        return generateStudentBuild(exams);
    };

    const isReadOnly = (typeof window !== 'undefined' && !!window.PLANNER_DATA) || import.meta.env.VITE_READ_ONLY === 'true';

    return {
        exams,
        addOrUpdateExam,
        deleteExam,
        stats: getStats(),
        importExams,
        exportExams,
        exportExamsToHtml: exportExamsToHtmlHandler,
        generateStudentBuild: generateStudentBuildHandler,
        isReadOnly
    };
};
